language: cpp

compiler:
 - gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install python libc6 libstdc++6 git subversion curl elfutils devscripts
 - git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git /tmp/depot_tools
 - export PATH="/tmp/depot_tools:$PATH"
 - git config --global user.email "ci-breakpad@example.com"
 - git config --global user.name "Breakpad CI"
 - mkdir /tmp/breakpad_root
 - cd /tmp/breakpad_root
 - gclient config --unmanaged --deps-file=DEPS https://github.com/primiano/breakpad.git --name=src
 - gclient sync -n

install:
 - cd /tmp/breakpad_root/src
 - echo $(pwd)
 - ls -la
 - ./configure
 - make -j4

script:
 - uname -a
 - ulimit -a
 - make -j4 check

after_failure:
 - cat test-suite.log

